# Generated by Django 5.1.4 on 2024-12-08 00:16

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=500)),
                (
                    "category",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("FEATURE", "Feature"),
                            ("CIRCUIT", "Circuit"),
                            ("UNIVERSALITY", "Universality"),
                            ("TECHNIQUES", "Techniques"),
                            ("OTHER", "Other"),
                        ],
                        max_length=45,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
