# Generated by Django 5.1.4 on 2024-12-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0002_paper_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="paper",
            name="tags",
            field=models.ManyToManyField(blank=True, to="papers.tag"),
        ),
    ]
