# Generated by Django 5.1.4 on 2024-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0003_tag_paper_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="paper",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
